services:
  frontend:
    container_name: frontend
    tty: true
    build: ./frontend
    networks:
      - to-do_app_network
    expose:
      - 3000
    ports:
      - "3000:3000"

  api:
    container_name: api
    tty: true
    build: ./api
    networks:
      - to-do_app_network
    expose:
      - 8080
    ports:
      - 8080:8080

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: to-do_app
    volumes:
      - to-do_app_volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - to-do_app_network
    expose:
      - 27017
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - to-do_app_network

networks:
  to-do_app_network:
    driver: bridge

volumes:
  to-do_app_volume:
